// styles.ts (TypeScript)
import { Dimensions, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 2,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    search: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    searchInput: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginVertical: 10,
        width: 300,
    },
    containerSmall: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center'
    },
    label: {
        fontWeight: 'bold',
        fontSize: 36,
        marginBottom: 20,
    },
    smartIDLabel: {
        fontSize: 20,
        backgroundColor: '#00b6ab',
        color: 'white',
        padding: 20,
        borderRadius: 20,
    },
    thinLabel: {
        fontSize: 36,
        marginBottom: 20,
    },
    input: {
        height: 43,
        borderColor: '#00b6ab',
        borderWidth: 2,
        width: '80%',
        marginBottom: 20,
        paddingLeft: 10,
        borderRadius: 20,
        backgroundColor: '#ffffff',
    },
    buttonImage: {
        width: 200,
        height: 60,
        resizeMode: 'contain',
    },
    image: {
        marginTop: 20,
        width: 400,
        height: 400,
        resizeMode: 'contain',
    },
    successText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'green',
    },
    smallText: {
        fontSize: 16,
        color: 'gray',
        padding: 10,
    },
    bigText: {
        fontSize: 32,
        flexWrap: 'wrap',
        textAlign: 'center',
        paddingHorizontal: 10,
        color: 'black',
        marginBottom:100,
    },
    smartIDText: {
        fontSize: 16,
        color: '#00b6ab',
        padding: 10,
    },
    smartIDLogo: {
        width: 150,
        height: 150,
        resizeMode: 'contain',
    },
    errorMessage: {
        color: 'red',
        marginTop: 10,
        textAlign: 'center',
    },
    confirmButton: {
        textAlign: 'center',
        fontSize: 16,
        backgroundColor: '#00b6ab',
        color: 'white',
        padding: 11,
        borderRadius: 20,
        marginBottom: 20,
    },
    code: {
        fontWeight: 'bold',
        fontSize: 40,
        marginBottom: 20,
    },
    top: {
        textAlign: 'center',
        flex: 1,
        justifyContent: 'flex-start', // Align children to the top
        padding: 20,
    },
    fileItem: {
        backgroundColor: '#bababa',
        padding: 10,
        borderRadius: 15,
        //width: '100%',
        marginVertical: 5,
        elevation: 3,
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
        alignItems: 'center',
    },
    buttonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    homeButtonsContainer: {
        marginTop: 10,
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#00b6ab',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
        marginHorizontal: 5,
        width: 42,
        height: 42,
    },
    searchButton: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#00b6ab',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
        marginHorizontal: 5,
        width: 42,
        height: 42,
    },
    deleteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f85959',
        paddingVertical: 12,
        paddingHorizontal: 13,
        borderRadius: 10,
        marginHorizontal: 5,
        width: 42,
        height: 42,
    },
    shareButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFD700',
        paddingVertical: 12,
        paddingHorizontal: 13,
        borderRadius: 10,
        marginHorizontal: 5,
        width: 42,
        height: 42,
    },
    downloadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#508eff',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
        marginHorizontal: 5,
        width: 42,
        height: 42,
    },
    signatureOrderButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ff69b4',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
        marginHorizontal: 5,
        width: 42,
        height: 42,
        justifyContent: 'center',  // Centers icon horizontally
    },
    buttonText: {
        color: '#fff',
        marginLeft: 5,
        fontSize: 14,
    },
    fileName: {
        fontWeight: 'bold',
        fontSize: 16,
        width: '100%',
    },
    pdfContainer: {
        flex: 1,
        height: Dimensions.get('window').height * 0.7,
    },
    pdfViewer: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    feedbackContainer: {
        marginTop: 20,
        marginHorizontal: 15,
        borderTopWidth: 1,
        borderTopColor: '#dcdcdc',
        paddingTop: 10,
    },
    feedbackText: {
        color: '#e23232',
        fontSize: 14,
    },
    reportContainer: {
        flex: 1,
        justifyContent: 'center',
        padding: 20,
        alignItems: 'center',
    },
    reportHeader: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
    },
    reportInput: {
        borderRadius: 10,
        height: 150,
        borderColor: '#ccc',
        borderWidth: 1,
        padding: 20,
        marginBottom: 20,
        textAlignVertical: 'top',
        width: "100%",
    },
    picker: {
        height: 43,
        borderColor: '#00b6ab',
        borderWidth: 2,
        width: '80%',
        marginBottom: 20,
        paddingLeft: 10,
        borderRadius: 20,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderWidth: 2,
        borderColor: '#00b6ab',
        borderRadius: 5,
        marginRight: 10,
    },
    checkboxSelected: {
        backgroundColor: '#00b6ab',
    },
});

export default styles;
